import 'dart:ui';

import 'package:hexcolor/hexcolor.dart';

const String SPLASH_SCREEN_ROUTE = "SPLASH_SCREEN_ROUTE";
const String SIGNUP_SCREEN_ROUTE = "SIGNUP_SCREEN_ROUTE";
const String LOGIN_SCREEN_ROUTE = "LOGIN_SCREEN_ROUTE";
const String HOME_SCREEN_ROUTE = "HOME_SCREEN_ROUTE";
const String COURSE_SCREEN_ROUTE = "COURSE_SCREEN_ROUTE";
const String MESSAGE_SCREEN_ROUTE = "MESSAGE_SCREEN_ROUTE";
const String ACCOUNT_SCREEN_ROUTE = "ACCOUNT_SCREEN_ROUTE";

